### ISSUE TITLE
Port campaign finance example?

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis-examples#8]
@nickcrews, would you be ok if we added a copy of your notebook from https://ibis-project.org/blog/rendered/campaign-finance/ to this environment as a runnable example? I'd need to make a few small changes to make things more usable in the resource restricted binder environment, but for the most part the example would be the same content as the blogpost. I'm happy to do the work, just looking for permission from you before starting.

**Comment by NickCrews** [comment]
That would be great! If you want to edit the blog post so it is more in line with the example, then go ahead there as well!
