### ISSUE TITLE
Add `ibis-substrait` example

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis-examples#9]
It'd be nice to have an example using `ibis-substrait` using the compiler to generate substrait and then run it with duckdb. We might be able to crib some of the example from [this blogpost](https://ibis-project.org/blog/ibis_substrait_to_duckdb/).

**Comment by danepitkin** [comment]
I can take this on if no one else has yet.

**Comment by jcrist** [comment]
Fixed by #16.
